export const CHOOSEAUTH = "CHOOSEAUTH";
export const SELECTEDAUTH = "SELECTEDAUTH";
export const REMOVESELECTEDAUTH = "REMOVESELECTEDAUTH";
export const ISRIGHTPANNELSHOW ="ISRIGHTPANNELSHOW";
export const EMPTYSELECTEDAUTJ = "EMPTYSELECTEDAUTJ";

export const ISINVITATIONPANELSHOW = "ISINVITATIONPANELSHOW";

export const CLOSERIGHTPANNEL = "CLOSERIGHTPANNEL";