export const CHOOSEAUTH = "CHOOSEAUTH";
export const SELECTEDAUTH = "SELECTEDAUTH";

export const ISRIGHTPANNELSHOW ="ISRIGHTPANNELSHOW";


export const ISINVITATIONPANELSHOW = "ISINVITATIONPANELSHOW";

export const CLOSERIGHTPANNEL = "CLOSERIGHTPANNEL";

export const USERCURRENTAPPPOLICY = "USERCURRENTAPPPOLICY";